### ISSUE TITLE
1. Wire frame/Project Mockup of Website

### ISSUE THREAD

**Issue by wangzi190** [wangzi190/flask_portfolio#4]
- [x] Mockup of home page with tabs
- [x] Layout of the individual tab pages
- [x] Color scheme
- [x] Mini lab pages
- [x] Brainstorm/plans

[Finished mockup](https://docs.google.com/presentation/d/1HNFrO9q06d981NLIgTWbwx9QG0fXWk9m49FlCKfe-d0/edit?usp=sharing)

**Comment by Nayanav** [comment]
![image](https://user-images.githubusercontent.com/34925114/132086273-76ab0bb4-b897-4c52-8b95-31aceaf5ea44.png)
![image](https://user-images.githubusercontent.com/34925114/132086286-b210e1ab-4166-4e22-b50f-8d9d4e56f143.png)
![image](https://user-images.githubusercontent.com/34925114/132086295-a80d1c36-ba56-476e-8367-9871981b3b4a.png)
![image](https://user-images.githubusercontent.com/34925114/132086299-c360cdce-42a3-44cd-ac0e-9532bd60bc17.png)
